version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3001:3000"
    volumes:
      - ./metabase-data:/metabase-data
    container_name: metabasee
    networks:
      - my-network

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    container_name: mongodbb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
